Fixed first solutions, added new solutions
js-tasks-ru/htmlcss-20210114_hajoff pull request #3
Opened 2021-01-25 10:02 UTC by orlovse

2021-01-25 10:51 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Hello world
+ вводная задача
```
```diff
Семантическая разметка страницы
+ семантическая разметка страницы
```
```diff
Кнопка
+ Кнопка
```
```diff
Аккордеон
+ Аккордеон
```
```diff
Гистограмма
+ Гистограмма
```
```diff
Скелетон
+ Скелетон
```

Добавляю преподавателя (@PDmitryA) для код-ревью, посмотрим что он скажет :)

2021-01-26 17:58 UTC, Thewhiterabbit123 commented
Привет! получилось хорошо. Давай поправим несколько замечаний?)

2021-01-26 19:21 UTC, Thewhiterabbit123 requested changes

2021-01-26 19:21 UTC, Thewhiterabbit123 commented on 03-lection1/01-button/button.css
> +  font-style: normal;
`font-style: normal;` стоит по-умолчанию, его можно не указывать

2021-01-26 19:21 UTC, Thewhiterabbit123 commented on 03-lection1/01-button/button.css
> +  height: 48px;
Лучше отступы сделать через `padding`. В этом случае, если будет несколько строк текста, его все равно будет видно

2021-01-26 19:21 UTC, Thewhiterabbit123 commented on 03-lection1/02-accordion/accordion.css
> +  margin-bottom: 8px;
По [БЭМу](https://ru.bem.info/methodology/quick-start/#блок) у блока не должны быть заданы внешние отступы.

> Блок не должен влиять на свое окружение, т. е. блоку не следует задавать внешнюю геометрию (в виде отступов, границ, влияющих на размеры) и позиционирование.

Можно задать блок-обертку, примиксовать элемент блока к акордеону и этому элементу задать отступы.
В примере ниже отступы будут заданы для `.wrapper__item`
```
<div class="wrapper">
   <div class="wrapper__item block"></div>
</div>
```

2021-01-26 19:21 UTC, Thewhiterabbit123 commented on 03-lection1/02-accordion/accordion.css
> +  font-weight: normal;
`font-style: normal;
  font-weight: normal;` - значения по-умолчанию, не нужно указывать

2021-01-26 19:21 UTC, Thewhiterabbit123 commented on 03-lection1/02-accordion/accordion.css
> +.accordion p {
`p` какой-то одинокий) давай класс добавим?)

2021-01-26 19:21 UTC, Thewhiterabbit123 commented on 04-lection2/01-histogram/histogram.css
> +/* .histagra, .cal {
кажется не нужно)

2021-01-26 19:21 UTC, Thewhiterabbit123 commented on 04-lection2/01-histogram/histogram.css
> +  font-style: normal;
тут тоже normal

2021-01-26 19:21 UTC, Thewhiterabbit123 commented on 04-lection2/01-histogram/histogram.css
> +.raw {
Вижу это элементом гистограммы. Скажи, ты специально выделил в блок?

2021-01-26 19:21 UTC, Thewhiterabbit123 commented on 04-lection2/01-histogram/histogram.css
> +.histogram p {
Обычно не используют такие селекторы при использовании БЭМа. Давай переделаем на классы?

2021-01-26 19:21 UTC, Thewhiterabbit123 commented on 04-lection2/01-histogram/index.html
> +                <p><a href="#">View all</a></p>
У ссылки осталась подводка, а на макете нет.
Убрать можно с помощью `text-decoration: none`

2021-01-26 19:21 UTC, Thewhiterabbit123 commented on 04-lection2/01-histogram/index.html
> +        </div>
Тут не хватает отступа под заголовком

2021-01-26 19:21 UTC, Thewhiterabbit123 commented on 04-lection2/02-skeleton/index.html
> +                <div class="skeleton__text title"></div>
title тут скорее как модификатор

Чтобы выделить элемент в отдельный бэм-блок, задаю себе вопрос - может ли он как-то использоваться отдельно, без компонента, в котором он изначально был

У `width: 172px;` сейчас очень мало стилей, правильнее его сделать как модификатор для `.skeleton__text`

```suggestion
                <div class="skeleton__text_title"></div>
```

или

```suggestion
                <div class="skeleton__text_type_title"></div>
```

2021-01-26 19:21 UTC, Thewhiterabbit123 commented on index.html
> +=======
Тут конфликты появились. Поправишь?
Пиши в личку если не получится)

2021-01-27 08:35 UTC, orlovse commented on 03-lection1/01-button/button.css
> +  font-style: normal;
А.. это я просто из фигмы скопировал css, понял, спасибо)

2021-01-27 08:44 UTC, orlovse commented on 03-lection1/01-button/button.css
> +  height: 48px;
ok

2021-01-27 08:48 UTC, orlovse commented on 03-lection1/02-accordion/accordion.css
> +  margin-bottom: 8px;
Понял, спасибо!

2021-01-27 08:50 UTC, orlovse commented on 04-lection2/01-histogram/histogram.css
> +/* .histagra, .cal {
да..торопился, забыл удалить)

2021-01-27 08:51 UTC, orlovse commented on 04-lection2/01-histogram/histogram.css
> +  font-style: normal;
Это всё фигма!))

2021-01-27 08:53 UTC, Thewhiterabbit123 commented on 04-lection2/01-histogram/histogram.css
> +  font-style: normal;
Я тоже так говорю всегда :D

2021-01-27 08:55 UTC, Thewhiterabbit123 commented on 03-lection1/01-button/button.css
> +  height: 48px;
Еще по поводу кнопки - обычно не указывают ей высоту, а задают паддинги. 
Если задать высоту, а текст не поместится в одну строку, то его не будет видно, а с паддингами будет

2021-01-27 09:17 UTC, Thewhiterabbit123 commented
Остался конфликт и ответить на [вопрос](https://github.com/js-tasks-ru/htmlcss-20210114_hajoff/pull/3#discussion_r564766064). :)

Все остальное ок!)

2021-01-29 10:00 UTC, orlovse commented on 04-lection2/01-histogram/histogram.css
> +.raw {
Не специально..сейчас назвал этот блок "histogram__info" - так лучше? =)

2021-01-29 10:01 UTC, orlovse commented on 04-lection2/01-histogram/histogram.css
> +.raw {
И по поводу конфликта в первом задании hello world , не понял как его исправить (

2021-01-30 15:31 UTC, Thewhiterabbit123 commented on 03-lection1/02-accordion/accordion.css
> +  background: #FFFFFF;
Background у акордиона планирует меняться при изменении темы, может тоже добавить переменную?

2021-01-30 15:31 UTC, Thewhiterabbit123 commented on 04-lection2/01-histogram/index.html
> +            <div class="link-wrapper">
В блоке не могут лежать  элементы другого блока, только его собственные. 
Можно например `histogram__link-wrapper`

2021-01-30 15:56 UTC, Thewhiterabbit123 requested changes

2021-01-30 15:56 UTC, Thewhiterabbit123 commented on 05-lection3/01-tooltip/tooltip.css
> +  position: relative;
Давай тут `cursor:pointer` добавим, а то не понятно что это интерактивный элемент)

2021-01-30 15:56 UTC, Thewhiterabbit123 commented on 05-lection3/01-tooltip/tooltip.css
> +  display: block;
тут `display: block;` не нужен, все равно ниже переопределяешь)

2021-01-30 15:56 UTC, Thewhiterabbit123 commented on 05-lection3/02-modal/modal.css
> +#modal {
id - только для js были нужны) По бэму селекторы должны быть на классах, давай переделаем)

2021-01-30 15:56 UTC, Thewhiterabbit123 commented on 05-lection3/02-modal/modal.css
> +  background-color: rgba(0, 0, 0, 0.4);
```suggestion
  background-color: rgba(0, 0, 0, 0.4);
```

Одна строчка перетирает другую) значит, одна из них не нужна)

2021-01-30 15:56 UTC, Thewhiterabbit123 commented on 05-lection3/03-calendar/index.html
> +        <div class="date__grid">
Календарь планировался одним бем-блоком, давай поменяем на элемент календаря)

2021-01-30 15:56 UTC, Thewhiterabbit123 commented on 06-lection4/01-avatar/avatar.css
> +  width: 116px;
Обычно самим блокам редко прописывают размеры, потому что они должны вписываться в контейнер любого размера. 

Либо размеры задают модификаторами, но тут предпочтительнее чтобы аватар был резиновым. Давай для него будем задавать ширину и высоту 100%, а контейнеру уже размеры

2021-01-30 15:56 UTC, Thewhiterabbit123 commented on 06-lection4/03-srcset/srcset.css
> +  object-fit: cover;
Давай тут класс добавим)

2021-01-30 15:56 UTC, Thewhiterabbit123 commented on components/page/template.css
> +.logo {
Давай отдельные бем-блоки выносить в отдельные файлы. Чтобы в каждом файле лежали только стили одного блока

2021-01-30 15:56 UTC, Thewhiterabbit123 commented on index.html
> +  <header class="main-page__header">
У меня почему-то для десктопного экрана логотип по центру, а должен быть слева
<img width="1680" alt="Снимок экрана 2021-01-30 в 18 54 04" src="https://user-images.githubusercontent.com/27774197/106360987-8968f500-632c-11eb-8e51-54242646a295.png">

2021-01-30 15:56 UTC, Thewhiterabbit123 commented on index.html
> +  <header class="main-page__header">
и календарик не влез в карточку

2021-01-31 06:34 UTC, orlovse commented on 05-lection3/01-tooltip/tooltip.css
> +  display: block;
ой, точно, в начале тестил и забыл убрать)

2021-01-31 06:41 UTC, orlovse commented on 05-lection3/02-modal/modal.css
> +  background-color: rgba(0, 0, 0, 0.4);
да.. что-то невнимательно делал, забыл удалить =)

2021-01-31 06:48 UTC, orlovse commented on 06-lection4/01-avatar/avatar.css
> +  width: 116px;
ок, понял)

2021-01-31 06:54 UTC, orlovse commented on 06-lection4/03-srcset/srcset.css
> +  object-fit: cover;
Это закоммитил, остальное попозже попытаюсь сделать. 
Спасибо!

2021-01-31 08:23 UTC, orlovse commented on components/page/template.css
> +.logo {
Я вынес лого и ещё контейнер(пользуюсь им в темплейте тоже). Этого достаточно или в отдельные файлы нужно и хэдер-футер-мэин ?

2021-01-31 08:23 UTC, orlovse commented on index.html
> +  <header class="main-page__header">
Вроде бы всё исправил, спасибо за правки!)

2021-02-01 12:26 UTC, Thewhiterabbit123 requested changes

2021-02-01 12:26 UTC, Thewhiterabbit123 commented on 03-lection1/02-accordion/accordion.css
> +  --main-text-color: #212429;
Уже все круто! не заметила в прошлый раз, давай поправим

Переменные у нас на весь проект одинаковые, давай создадим файлик, например `variables`, и туда сложить все переменные, чтобы определить их один раз, а потом использовать во всех компонентах

2021-02-01 12:26 UTC, Thewhiterabbit123 commented on 05-lection3/03-calendar/calendar.css
> +.calendar__grid-item:nth-child(19),
я бы тут, конечно, сделала модификаторами)

2021-02-01 12:26 UTC, Thewhiterabbit123 commented on components/border.css
> +.border {
Какой логический смысл этого блока?)
Может использоваться сам по себе? 
если нет, тогда это модификатор)

2021-02-01 12:26 UTC, Thewhiterabbit123 commented on components/calendar.css
> +.calendar-mini,
mini - модификатор?) можно быть тогда `calendar__mini`)

2021-02-01 12:26 UTC, Thewhiterabbit123 commented on components/modal.css
> +.modal-open {
нейминг элементов - 
```modal__open```

2021-02-01 12:26 UTC, Thewhiterabbit123 commented
Давай еще подходик и вмержим))

2021-02-02 08:14 UTC, orlovse commented on 03-lection1/02-accordion/accordion.css
> +  --main-text-color: #212429;
точно!

2021-02-02 08:41 UTC, orlovse commented on components/border.css
> +.border {
Подумал, что он используется в нескольких компонентах и его можно вынести в отдельную сущность, чтобы можно было подключать к любому из них. Например если нужно будет изменить стиль рамки, то можно поменять его только в одном месте и он автоматически изменится у всех компонентов, использующих её. Разве не лучше так оставить?)

2021-02-02 08:42 UTC, orlovse commented on components/calendar.css
> +.calendar-mini,
даа.. с бэмом у меня проблемы))

2021-02-02 08:46 UTC, orlovse commented on components/modal.css
> +.modal-open {
Вроде бы всё, только border пока оставил по прежнему, жду комментария)

2021-02-03 15:27 UTC, Thewhiterabbit123 commented on components/border.css
> +.border {
Вообще я с тобой согласна) можно оставить это так)

2021-02-03 15:29 UTC, n-parpibaeva approved these changes

2021-02-03 16:56 UTC, merged